_wandb:
    value:
        cli_version: 0.23.0
        e:
            ja2pdecf7hgaouy2cfvdqn8fw5kjxcco:
                codePath: c:\Users\salma\Documents\llm_ai_projects\week6\day5.ipynb
                codePathLocal: day5.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "510745636864"
                        used: "340223590400"
                email: salthecoder11@gmail.com
                executable: c:\Users\salma\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 6b53947eb51682df8076118ef247b1f5ec923039
                    remote: https://github.com/SalDev1/llm-ai-projects.git
                gpu: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                      uuid: GPU-e6e68154-459a-7b81-bf91-f54002e9cf40
                host: salmanacer
                memory:
                    total: "16438312960"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\salma\Documents\llm_ai_projects\week6\day5.ipynb
                python: CPython 3.13.0
                root: c:\Users\salma\Documents\llm_ai_projects\week6
                startedAt: "2025-11-15T16:33:26.133866Z"
                writerId: ja2pdecf7hgaouy2cfvdqn8fw5kjxcco
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 95
                - 97
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 95
                - 97
                - 105
            "3":
                - 2
                - 13
                - 14
                - 58
                - 61
                - 62
            "4": 3.13.0
            "5": 0.23.0
            "6": 4.57.1
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
created_at:
    value: "2025-11-15 21:40:40"
error:
    value:
        code: null
        message: null
        param: null
estimated_finish:
    value: null
eval_id:
    value: null
fine_tuned_model:
    value: ft:gpt-4o-mini-2024-07-18:salman:pricer:CcDIm7Z3
finished_at:
    value: "2025-11-15 21:50:30"
hyperparameters:
    value:
        batch_size: 1
        learning_rate_multiplier: 1.8
        n_epochs: 1
id:
    value: ftjob-Bg3MID9R2lVShfyvoZi6JYcM
integrations:
    value:
        - FineTuningJobWandbIntegrationObject(type='wandb', wandb=FineTuningJobWandbIntegration(project='gpt-pricer', entity=None, name=None, tags=None, run_id='ftjob-Bg3MID9R2lVShfyvoZi6JYcM'))
metadata:
    value: null
method:
    value: Method(type='supervised', dpo=None, reinforcement=None, supervised=SupervisedMethod(hyperparameters=SupervisedHyperparameters(batch_size=1, learning_rate_multiplier=1.8, n_epochs=1)))
model:
    value: gpt-4o-mini-2024-07-18
n_train:
    value: 200
n_valid:
    value: 50
object:
    value: fine_tuning.job
organization_id:
    value: org-16HRO86xPnKe8TTU0DN1mvuI
result_files:
    value: file-49aiAvRpUKZFJzxKD91Ro8
seed:
    value: 42
shared_with_openai:
    value: false
status:
    value: succeeded
trained_tokens:
    value: 39235
training_file:
    value: file-W9hXXKm9NJ42VvzLm3Ww7q
usage_metrics:
    value: null
user_provided_suffix:
    value: pricer
validation_file:
    value: file-TRqEMLiKSNSZ4k1BnDHtPC
